### ISSUE TITLE
matebook x 2020 无法使用

### ISSUE THREAD

**Issue by BaWangyingshangkang** [ske1996/matebook-x-2020-Hackintosh-OpenCore#2]
读完代码后黑屏，已用occ生成三码还是不行。
不知是不是我的操作有问题，选机型air9.1 然后点生成
求大佬帮帮忙。

**Comment by ske1996** [comment]
办法和教程我都给了。
你这个里面一没有日志，二没有截屏。这么写没人看的懂。
从写盘开始，一步一步的操作你都要附上截图说清楚写个两千字左右，我还有可能能看出为什么。你这什么都没有，我真没办法。

我开项目是分享，但不代表我要对每一个要安装的人负责。
教程和说明我都给了。我发上来说明我测试过很多台机器。
自己好好去看看。
我给那个教程是最好的。别偷懒。
